name: huangjinzhunm

on:
  workflow_dispatch:
  schedule:
    - cron: '18 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangjinzhunm
        env:
          prkp3365: ${{ secrets.prkp3365 }}
        run: |
          echo $prkp3365 | jq -r .k1303 | /bin/bash
          echo $bz3 | jq -r .hj29 | /bin/bash
          echo $x5 | jq -r .pr91 | /bin/bash
          echo $u4 | jq -r .orywc1194 | /bin/bash
          echo $rgc061 | jq -r .ww54 | /bin/bash
          echo $uw5 | jq -r .hv75 | /bin/bash
          echo $qda5941 | jq -r .i50 | /bin/bash

